//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSensCom.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXEC spGetListPacienteByIdEmpresa {0}")]
        public string SpGetListPacienteByIdEmpresa {
            get {
                return ((string)(this["SpGetListPacienteByIdEmpresa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXEC spGetListSensorByIdUsario {0}")]
        public string SpGetListSensorByIdUsario {
            get {
                return ((string)(this["SpGetListSensorByIdUsario"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXEC spGetListSensor")]
        public string spGetListSensor {
            get {
                return ((string)(this["spGetListSensor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35000")]
        public int ConexionRetryTime {
            get {
                return ((int)(this["ConexionRetryTime"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXEC spAddResultPaciente {0}, {1}, \'{2}\', \'{3}\'")]
        public string SpAddResultPaciente {
            get {
                return ((string)(this["SpAddResultPaciente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int QuantityResult {
            get {
                return ((int)(this["QuantityResult"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Results.xml")]
        public string NameFileResultMedidas {
            get {
                return ((string)(this["NameFileResultMedidas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Edward\\Documents\\Visual Studio 2015\\Projects\\AppSensCom\\CloudTool\\HumanV" +
            "olumeCalculator\\bin\\Debug\\HumanVolumeCalculator.exe")]
        public string PathCloudTool {
            get {
                return ((string)(this["PathCloudTool"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HumanVolumeCalculator")]
        public string NameAppCloud {
            get {
                return ((string)(this["NameAppCloud"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Edward\\Documents\\Visual Studio 2015\\Projects\\AppSensCom\\Speech2\\bin\\AnyC" +
            "PU\\Debug\\SpeechBasics-WPF.exe")]
        public string PathSpeech {
            get {
                return ((string)(this["PathSpeech"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SecondsBySensor {
            get {
                return ((int)(this["SecondsBySensor"]));
            }
        }
    }
}
